import { sampleDeals, forecast, sampleBills, sampleReceipts, purchaseOrders, reconcile } from "@/lib/operations";
import { eur } from "@/components/workspace-shell";

export default function ProjectPreview({ kind }: { kind: "revenue" | "purchasing" | "research" | "platform" }) {
  const totals = forecast(sampleDeals);
  const invoices = reconcile(purchaseOrders, sampleReceipts, sampleBills, 2);
  return <div className="project-preview" aria-label={kind === "research" || kind === "platform" ? "System overview" : "Preview with fictional sample data"}>
    <div className="flex items-center justify-between gap-3 border-b border-white/10 pb-3 mb-5"><span className="text-xs font-medium tracking-wide text-gray-300">{({revenue:"REVENUE DESK",purchasing:"PURCHASING CONTROL",research:"OPPORTUNITY INTELLIGENCE",platform:"AUTOMATION PLATFORM"})[kind]}</span><span className="text-[10px] text-gray-500">{kind === "revenue" || kind === "purchasing" ? "Sample workspace" : "System overview"}</span></div>
    {kind === "revenue" && <><div className="grid grid-cols-2 gap-3 mb-5"><div><p className="text-[10px] text-gray-500">Open pipeline</p><p className="text-2xl font-semibold mt-1 text-white">{eur(totals.open)}</p></div><div><p className="text-[10px] text-gray-500">Weighted forecast</p><p className="text-2xl font-semibold mt-1 text-green-300">{eur(totals.weighted)}</p></div></div><div className="grid grid-cols-3 gap-2">{["New","Qualified","Proposal"].map((stage) => <div key={stage} className="bg-white/[.03] rounded-lg p-3 border border-white/5"><p className="text-[10px] text-gray-500 mb-3">{stage}</p><p className="text-xs text-gray-200">{sampleDeals.find((deal) => deal.stage === stage)?.company}</p><div className="h-1 rounded bg-green-400/30 mt-4" /></div>)}</div></>}
    {kind === "purchasing" && <><div className="flex gap-8 mb-4"><div><p className="text-[10px] text-gray-500">Invoices checked</p><p className="text-2xl mt-1 text-white">{invoices.length}</p></div><div><p className="text-[10px] text-gray-500">Held for review</p><p className="text-2xl mt-1 text-amber-300">{invoices.filter((row) => !row.ready).length}</p></div></div>{invoices.slice(0,3).map((row) => <div key={row.id} className="flex justify-between gap-3 text-xs py-3 border-t border-white/5"><span className="text-gray-300">{row.supplier}</span><span className={row.ready ? "text-green-300" : "text-amber-300"}>{row.ready ? "Matched" : "Review needed"}</span></div>)}</>}
    {kind === "research" && <div className="space-y-3">{[["01","Multi-source collection","Gather"],["02","Relevance & duplicate checks","Filter"],["03","Ranked shortlist","Review"]].map(([n,title,status]) => <div key={n} className="flex items-center gap-3 rounded-lg p-3.5 bg-white/[.03] border border-white/5"><span className="text-green-400 text-xs">{n}</span><span className="text-xs text-gray-300 flex-1">{title}</span><span className="text-[10px] text-gray-500">{status}</span></div>)}</div>}
    {kind === "platform" && <><div className="text-center rounded-lg border border-green-400/20 bg-green-400/5 p-4 text-sm text-green-300">Controlled access</div><div className="grid grid-cols-3 gap-2 my-3">{["Applications","AI workflows","Integrations"].map((item) => <div key={item} className="rounded-lg p-4 text-center border border-white/10 text-[11px] text-gray-300">{item}</div>)}</div><div className="text-center rounded-lg border border-white/10 p-4 text-xs text-gray-500">Isolated services · Repeatable deployment</div></>}
  </div>;
}
