import Link from "next/link";
import ProjectPreview from "@/components/project-preview";
const projects = [
  { title: "Revenue Desk", category: "Sales operations", kind: "revenue" as const, description: "From the first enquiry to an approved proposal. A connected workspace for pipeline management, pricing, and the decisions that move a deal forward.", capabilities: "Quote builder · Approval rules · Revenue forecast", href: "/projects/revenue-desk", action: "Explore the workspace", status: "Working prototype" },
  { title: "Purchasing Control", category: "Finance & operations", kind: "purchasing" as const, description: "Catch the mismatch before approving the invoice. Match purchase orders, deliveries, and supplier bills, with a clear path for resolving exceptions.", capabilities: "Three-way matching · Exception review · Approval history", href: "/projects/purchasing-control", action: "Explore the workspace", status: "Working prototype" },
  { title: "Opportunity Intelligence", category: "Research automation", kind: "research" as const, description: "A scheduled research pipeline that brings scattered opportunities into one place, checks relevance, and produces a shortlist worth acting on.", capabilities: "Multi-source research · Ranking · Duplicate detection", href: "/projects/opportunity-intelligence", action: "View project", status: "Private project" },
  { title: "Private Automation Platform", category: "Cloud & infrastructure", kind: "platform" as const, description: "The foundation for running connected applications and AI workflows, with controlled access, isolated services, and repeatable deployment.", capabilities: "Access controls · Service isolation · Operations", href: "/projects/automation-platform", action: "View project", status: "Private project" },
];
export default function Projects() {
  return <section id="projects" aria-labelledby="projects-title" className="py-14 scroll-mt-8"><div className="mb-10"><p className="text-sm text-green-400 mb-3">Selected work</p><h2 id="projects-title" className="text-3xl sm:text-4xl font-semibold">Built around the whole workflow.</h2><p className="mt-4 text-gray-400 max-w-2xl">Business software, research automation, and the infrastructure behind them.</p></div>
    <div className="grid md:grid-cols-2 gap-7">{projects.map((project) => <article key={project.title} className="project-feature group"><Link href={project.href} className="block" aria-label={`Explore ${project.title}`}><ProjectPreview kind={project.kind} /></Link><div className="p-6 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-2 text-xs mb-4"><span className="text-green-400">{project.category}</span><span className="text-gray-500">{project.status}</span></div><h3 className="text-2xl font-semibold">{project.title}</h3><p className="text-gray-400 leading-relaxed mt-3">{project.description}</p><p className="text-xs text-gray-500 mt-5">{project.capabilities}</p><Link href={project.href} className="inline-flex gap-5 items-center text-green-400 text-sm mt-6">{project.action}<span aria-hidden="true">↗</span></Link></div></article>)}</div>
    <div className="mt-8 rounded-xl border border-white/10 p-5 sm:p-6 flex flex-wrap justify-between items-center gap-5"><div><h3 className="font-medium">More hands-on projects</h3><p className="text-sm text-gray-500 mt-1">Smaller tools for everyday business tasks.</p></div><div className="flex flex-wrap gap-6 text-sm text-green-400"><Link href="/projects/invoice-follow-up">Invoice follow-up ↗</Link><Link href="/projects/lead-routing">Lead intake & routing ↗</Link></div></div>
  </section>;
}
